### ISSUE TITLE
Suggestion: Add a Note About jq Requirement During Installation

### ISSUE THREAD

**Issue by pazdzioch78** [NodeMafia/NillionNodeGuide#1]
Hi team,

I noticed that some users face issues during the installation process because they don't have `jq` installed in their system. This can cause errors or prevent the setup from completing successfully. It would be helpful to include a note in the installation guide specifying that `jq` is a required dependency and provide instructions on how to install it.

For example:

```bash
# Install jq on Ubuntu/Debian
sudo apt-get update
sudo apt-get install jq

**Comment by NodeMafia** [comment]
Hello [pazdzioch78](https://github.com/pazdzioch78),
Added a line to check <jq>. Thanks for the comment.
```
# Check if jq is installed, if not install it
if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Installing jq..."
    sudo apt update
    sudo apt install -y jq
fi
```
